version: '3'
service:
  db:
    build: ../thesis-155
    dockerfile: Dockerfile
    container_name: db_server
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      vpcbr:
        ipv4_address: 172.20.0.5
      
  adminer:
    image: adminer:4.7.5-standalone
    container_name: db_admin
    ports:
      - "10081:8080"
    networks:
      vpcbr:
        ipv4_address: 172.20.0.10

volumes:
  db_data:

networks: 
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1 

