FROM postgres:12.1-alpine

USER postgres

ENV POSTGRES_PASSWORD P@$$0rd

VOLUME vol-thesis-155:/var/lib/postgresql/data
# VOLUME /vol-thesis-155:/var/lib/postgresql/data   #สามารถใช้แบบนี้ได้เช่นกัน


EXPOSE 5432
WORKDIR /home 


