version: "3"
services:
  api:
    build:
      context: ./dockerfiles
      dockerfile: nodeapp/Dockerfile
    image: thesis-184:node-app
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
  
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus-data:/prometheus-data
    command: "--config.file=/prometheus-data/prometheus.yml"

  c_advisor:
    image: google/cadvisor:latest
    ports:
      - 20080:8080
    volumes: 
      - /:rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro

  nifi:
    image: apache/nifi:1.10.0
    ports:
      - 10090:10090
    environment:
      - NIFI_WEB_HTTP_PORT=10090
      - NIFI_JVM_HEAP_INIT=256m
      - NIFI_JVM_HEAP_MAX=3g

networks:
  default:
    external:       
      name: thesis-184

