version: "3"
services:
  api:
    build:
      context: ./dockerfiles
      dockerfile: nodeapp/Dockerfile
    image: thesis-184:node-app
    volumes:
      - .:/usr/src/app
    ports:
      - 30080:80
      - 3000:3000
  
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus-data:/prometheus-data
    # networks: 
    #   - thesis-184
    command: "--config.file=/prometheus-data/prometheus.yml"

# networks: 
#   thesis-184:
#     driver: bridge

networks:
  default:
    external:       
      name: thesis-184

